### ISSUE TITLE
Joints dont line up.

### ISSUE THREAD

**Issue by eraldylli** [jomettler/Trident-Experimental#1]
When trying to derack the gantry, the joints don't line up as they should, when the gantry is pulled all the way forward. Other than that, which I worked around, this github equiped me with all I needed for my fully MGN12H Trident. Thanks!

**Comment by jomettler** [comment]
Hi, 
please excuse the late reply. I´m glad it worked for you in the end, but what do you mean with "the joints don´t line up as they should"? I remeasured the joints both on my trident and in CAD and they seem fine. Am I missing something? 
Thank you very much for your feedback!

Best,

**Comment by eraldylli** [comment]
Hi, I cant take pictures right now, but I will try to explain what I mean.
When trying to derack the gantry, If both xy joints touch the motor mounts, the x rail shifts at an angle of 7-10 degrees.
If the x rail is perfectly perpendicular to the xy joints, the left one is ahead by an inch or so.
Do I make myself understood? I'm having trouble explaining it better than this.

**Comment by eraldylli** [comment]
Btw, I really appreciate your work, hence the reporting of this issue (which can be happening to me alone).

**Comment by jomettler** [comment]
Ok, I think I get what you mean. I still can not reproduce it either in CAD or my machine. Is your frame and rail alignment square?
With CoreXY (and my impression is its worse on QuadAB) its also possible you pull it out of square by increasing belt tension. I used zip ties to keep my X axis all the way in the back and not accidentally rack it. Also, motors must be powered off and ideally be unplugged.

CAD pictures to clarify what I understand is your problem: Either they would be at an angle at the same position, or the distance to the AB mounts would be unequal at same X position. Both not the case.
![image](https://user-images.githubusercontent.com/80679433/204321653-ddcd6e08-41fa-4d8f-970a-1dbe3e98c4b0.png)
![image](https://user-images.githubusercontent.com/80679433/204321689-6d29a9f3-b8ee-4d67-8450-a0488b301b12.png)
![image](https://user-images.githubusercontent.com/80679433/204321708-09f411a6-f483-4c1c-a973-657143d36d48.png)

Always happy about issues and feedback, thank you!

**Comment by eraldylli** [comment]
Thanks for the screenshots. Makes it far more simple, and yes you understood exactly what I meant. Im not sure If im using an old version (downloaded 4 months ago) or there is a discrepancy in the way the CAD shows it, but I couldnt reproduce this.
Managed to take some (blurry) photos to show what the problem could come from. This is the joints seen from below. Notice that the rail carriage on the left joint (2nd picture) sticks out about 8-10mm more than the left carriage (1st picture). Maybe the joints are not supposed to be identical... But if they are supposed to be identical, this might indicate towards the reason they are not. What do you think?

![20221128_170033](https://user-images.githubusercontent.com/88282396/204324550-633db418-5456-47ae-919f-b2df38c3366e.jpg)

![20221128_170050](https://user-images.githubusercontent.com/88282396/204324590-17595e4b-151c-4d67-97d7-78e2470416dd.jpg)

**Comment by eraldylli** [comment]
Btw the endstop pod thingy I have modified myself, because I needed one for mgn12 carriages and I couldnt find any online.

**Comment by jomettler** [comment]
AH, THANK YOU! Now I see, this is indeed an error in design, will fix!

**Comment by jomettler** [comment]
Fixed with 2ce88e33a6c15cfb72dc684c81c14851864f44c6
